{{- $commonName := include "common.names.fullname" . }}
{{- $commonLabelsStandard := include "common.labels.standard" . }}
{{- $commonLabels := .Values.commonLabels }}
{{- $commonAnnotations := .Values.commmonAnnotations }}
{{- $namespace := .Release.Namespace | quote }}
{{- $global := .Values.global }}

{{- range .Values.secrets }}
---
{{- $name := .name }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
  labels: {{- $commonLabelsStandard | nindent 4 }}
    {{- if $commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" $commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .annotations $commonAnnotations }}
  annotations:
    {{- if .annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .persistence.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if $commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" $commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
stringData:
  {{- .data | toYaml | nindent 2 }}
{{- end }}